name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Go to the app directory
            cd ~/Alt-Text

            # Pull latest change
            git pull origin main
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

            # Optional: activate virtual environment
            source venv/bin/activate || python3 -m venv venv && source venv/bin/activate

            # Install requirements
            pip install --upgrade pip
            pip install -r requirements.txt

            # Restart Streamlit app (using nohup here)
            pkill streamlit || true
            nohup streamlit run app.py --server.port 8502 > output.log 2>&1 &
            # nohup streamlit run app.py --server.port 8502 --server.headless true > streamlit.log 2>&1 &
          EOF
